
#ifndef MSG2133_TOUCHPANEL_H__
#define MSG2133_TOUCHPANEL_H_

#define TPD_RES_X (320)
#define TPD_RES_Y (480)
#define TPD_HAVE_BUTTON
#define TPD_BUTTON_HEIGHT        (30)
#define TPD_BUTTON_WIDTH         (40)
#define TPD_KEY_COUNT            3
#define TPD_KEYS                {KEY_MENU,KEY_BACK,KEY_HOMEPAGE }
#define TPD_KEYS_DIM            {{55,525,TPD_BUTTON_WIDTH,TPD_BUTTON_HEIGHT},{160,525,TPD_BUTTON_WIDTH,TPD_BUTTON_HEIGHT},{265,525,TPD_BUTTON_WIDTH,TPD_BUTTON_HEIGHT}}

#define MAX_TOUCH_FINGER 		3
#define REPORT_PACKET_LENGTH   8
#define MS_TS_MSG21XX_X_MAX  		TPD_RES_X
#define MS_TS_MSG21XX_Y_MAX		TPD_RES_Y
#endif

